import tweepy
from ai.tweet_generator import generate_tweet
import time

# Load Twitter API keys from config
import json
with open("config.json") as f:
    config = json.load(f)

auth = tweepy.OAuthHandler(config['api_key'], config['api_key_secret'])
auth.set_access_token(config['access_token'], config['access_token_secret'])
api = tweepy.API(auth)

def tweet_clan_message(clan_name, custom_message=""):
    """
    Tweets a message generated by AI for the specified clan.
    :param clan_name: str, name of the clan (Uzumaki, Hyuga, Senju, Uchiha)
    :param custom_message: str, custom message to append
    """
    tweet = generate_tweet(clan_name, custom_message)
    try:
        api.update_status(tweet)
        print(f"Tweeted: {tweet}")
    except tweepy.TweepError as e:
        print(f"Error: {e}")

def auto_tweet():
    """
    Automatically tweet from all clans at intervals.
    """
    clans = ["Uzumaki", "Hyuga", "Senju", "Uchiha"]
    while True:
        for clan in clans:
            tweet_clan_message(clan, "Join us on this journey!")
            time.sleep(3600)  # Sleep for 1 hour between tweets
